### ISSUE TITLE
Problems with "jsf-22-write-custom-renderer-skeleton" (http://www.omnifaces-fans.org/2015/02/jsf-22-write-custom-renderer-skeleton.html)

### ISSUE THREAD

**Issue by tcrook1812** [AnghelLeonard/JSF-2.2#1]
Hello there Anghel.

FYI, I downloaded JSF-2.2-master.zip. This contained a lot projects with maven references to jsfgroup, which is referenced as version 2.3. Maven was unable to resolve the jar file in projects which are associated with JSF 2.3. Would it be a lot to ask to keep JSF 2.3 projects elsewhere, since this the GitHub project name says it all - JSF-2.2-master?

When I tried building CustomRendererSkeleton_3, there were problems with faces-config.xml under the element render-kit. Is there a missing file in the resources directory or do I need to pull down something from Eclipse MarketPlace?

Here's the error:
*_Description   Resource    Path    Location    Type
cvc-complex-type.2.4.a: Invalid content was found starting with element 'render-kit'. One of '{"http://xmlns.jcp.org/xml/ns/javaee":action-listener, "http://xmlns.jcp.org/xml/ns/javaee":default-render-kit-id, "http://xmlns.jcp.org/xml/ns/javaee":message-bundle, "http://xmlns.jcp.org/xml/ns/javaee":navigation-handler, "http://xmlns.jcp.org/xml/ns/javaee":view-handler, "http://xmlns.jcp.org/xml/ns/javaee":state-manager, "http://xmlns.jcp.org/xml/ns/javaee":el-resolver, "http://xmlns.jcp.org/xml/ns/javaee":property-resolver, "http://xmlns.jcp.org/xml/ns/javaee":variable-resolver, "http://xmlns.jcp.org/xml/ns/javaee":resource-handler, "http://xmlns.jcp.org/xml/ns/javaee":resource-library-contracts, "http://xmlns.jcp.org/xml/ns/javaee":system-event-listener, "http://xmlns.jcp.org/xml/ns/javaee":locale-config, "http://xmlns.jcp.org/xml/ns/javaee":resource-bundle, "http://xmlns.jcp.org/xml/ns/javaee":application-extension, "http://xmlns.jcp.org/xml/ns/javaee":default-validators}' is expected.    faces-config.xml    /CustomRendererSkeleton_3/src/main/webapp/WEB-INF   line 8  XML Problem
*_
Thanks for your time putting this together.

**Comment by AnghelLeonard** [comment]
Hi,

   You ca find the JSF 2.3 projects here: https://github.com/AnghelLeonard/JSF-2.3. Yes, you right the JSF 2.3 projects should be removed from here. I'll do it shortly.

  Have you tried to run the app on GlassFish 4.1?

**Comment by tcrook1812** [comment]
Hello again Anghel.
I am actually using WildFly/JBoss as my server.

Date: Fri, 5 Feb 2016 00:26:02 -0800

**Comment by AnghelLeonard** [comment]
I have upload a version tested on WildFly. Hope it work for you too.
https://github.com/AnghelLeonard/JSF-2.2/tree/master/CustomRendererSkeleton_3_WF

**Comment by tcrook1812** [comment]
Thanks Anghel.

-------- Original message --------

**Comment by tcrook1812** [comment]
One problem I am having is resolving jsf22-2.2.jar. I tried running "mvn install" to download this jar file, but it didn't work. I am using WildFly 8.2.1 Final as my server. I guess I need to get maven to resolve this jar reference to jsf-impl-2.2.8-jbossorg-1.jar in WildFly.

Date: Mon, 8 Feb 2016 23:46:48 -0800

**Comment by AnghelLeonard** [comment]
The solution will be to manually install the JSF 2.2 artifact. Bascially this is possible in NetBeans and Eclipse also very easy. Simply take the JAR from here:https://github.com/AnghelLeonard/JSF-2.2/tree/master/CustomRendererSkeleton_3_WF/target/CustomRendererSkeleton_3_WF-1.0/WEB-INF/lib and install it as a local dependency. Hope it helps!

**Comment by tcrook1812** [comment]
There are some other issues:
In faces-config.xml, for JSF 2.2, the render-kit element should be a sibling element of application, not a child. Maybe the XML schema has changed for JSF 2.3, but this is the way it is for JSF 2.2.
In pom.xml, the entry for jsf22 should have its scope set to provided, as it shouldn't be copied into the deployment.

Date: Tue, 9 Feb 2016 21:54:10 -0800

**Comment by AnghelLeonard** [comment]
Yep! You right ;)
